local opt = vim.opt

opt.cindent = true
opt.confirm = true
opt.cursorline = true
opt.expandtab = true
opt.exrc = true
opt.guicursor = "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20,t:ver25-blinkon500-blinkoff500-TermCursor"
opt.ignorecase = true
opt.mousemoveevent = true
opt.number = true
opt.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
opt.shiftwidth = 4
opt.signcolumn = "yes"
opt.smartcase = true
opt.softtabstop = 2
opt.smoothscroll = true
opt.spell = true
opt.termguicolors = true
opt.winborder = "rounded"
